# Generated by Django 5.0.4 on 2024-05-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_abonadossten_ingresossten_traficosten'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abonado',
        ),
        migrations.DeleteModel(
            name='AbonadosSten',
        ),
        migrations.DeleteModel(
            name='Ingresos',
        ),
        migrations.DeleteModel(
            name='IngresosSten',
        ),
        migrations.DeleteModel(
            name='TRAFICO',
        ),
        migrations.DeleteModel(
            name='TraficoSten',
        ),
    ]
