# Generated by Django 5.0.4 on 2024-05-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='hora',
        ),
    ]
