# Generated by Django 5.0.4 on 2024-05-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_turno_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
