# Generated by Django 5.0.4 on 2024-05-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_turno_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='Persona',
            field=models.CharField(max_length=100),
        ),
    ]
